export const mockdata = {
  notices: [
    {
      id: 0,
      title: "need a carjack in the weekend in skinnarila region!",
      type: "looking for...",
      ingress: "lorem upsum",
      description:
        "additional information and description related to the notice. lorem ipsum dolor sit amet, consectetur adipiscing elit. vestibulum consequat efficitur felis, ut feugiat justo cursus et. maecenas dapibus dictum eros vel lacinia. proin suscipit posuere purus vitae eleifend. maecenas mauris elit, porttitor et magna vel, venenatis egestas diam. aliquam eleifend dictum iaculis. nunc placerat tortor orci, id commodo nisl pulvinar mattis. duis a sem consequat eros ornare feugiat. proin tempor arcu feugiat dignissim maximus. pellentesque tincidunt congue odio, ac gravida nulla. aliquam eu iaculis massa. donec vitae dui ut eros fermentum suscipit quis id nibh. proin et posuere libero. suspendisse potenti. nulla ornare viverra massa sed molestie. fusce dignissim tellus scelerisque aliquam efficitur.",
      nickname: "carjacker22",
      image: "/two_kittens.png",
      area: "Skinnarila",
      timedate: "11/01/2024, 12:13",
      location: "approximate location here, not sure how it should be saved",
    },
    {
      id: 1,
      title: "dog walking company",
      type: "looking for...",
      ingress: "2 year old Samoyed looking for walking buddies!",
      description:
        "additional information and description related to the notice. lorem ipsum dolor sit amet, consectetur adipiscing elit. vestibulum consequat efficitur felis, ut feugiat justo cursus et. maecenas dapibus dictum eros vel lacinia. proin suscipit posuere purus vitae eleifend. maecenas mauris elit, porttitor et magna vel, venenatis egestas diam. aliquam eleifend dictum iaculis. nunc placerat tortor orci, id commodo nisl pulvinar mattis. duis a sem consequat eros ornare feugiat. proin tempor arcu feugiat dignissim maximus. pellentesque tincidunt congue odio, ac gravida nulla. aliquam eu iaculis massa. donec vitae dui ut eros fermentum suscipit quis id nibh. proin et posuere libero. suspendisse potenti. nulla ornare viverra massa sed molestie. fusce dignissim tellus scelerisque aliquam efficitur.",
      nickname: "dogwalker22",
      image: "/samoyed.jpg",
      area: "Kourula",
      timedate: "11/01/2024, 12:13",
      location: "approximate location here, not sure how it should be saved",
    },
    {
      id: 2,
      title: "a bass player needed for a punk band!",
      type: "looking for...",
      ingress: "Practises held on Thursdays, come try out!",
      description:
        "additional information and description related to the notice. lorem ipsum dolor sit amet, consectetur adipiscing elit. vestibulum consequat efficitur felis, ut feugiat justo cursus et. maecenas dapibus dictum eros vel lacinia. proin suscipit posuere purus vitae eleifend. maecenas mauris elit, porttitor et magna vel, venenatis egestas diam. aliquam eleifend dictum iaculis. nunc placerat tortor orci, id commodo nisl pulvinar mattis. duis a sem consequat eros ornare feugiat. proin tempor arcu feugiat dignissim maximus. pellentesque tincidunt congue odio, ac gravida nulla. aliquam eu iaculis massa. donec vitae dui ut eros fermentum suscipit quis id nibh. proin et posuere libero. suspendisse potenti. nulla ornare viverra massa sed molestie. fusce dignissim tellus scelerisque aliquam efficitur.",
      nickname: "guitarplayer22",
      image: "/turtle.jpg",
      area: "skinnarila",
      timedate: "11/01/2024, 12:13",
      location: "approximate location here, not sure how it should be saved",
    },
    {
      id: 3,
      title: "Sewing services for student overalls or other clothing!",
      type: "Offering...",
      ingress: "Costs need to be covered",
      description:
        "additional information and description related to the notice. lorem ipsum dolor sit amet, consectetur adipiscing elit. vestibulum consequat efficitur felis, ut feugiat justo cursus et. maecenas dapibus dictum eros vel lacinia. proin suscipit posuere purus vitae eleifend. maecenas mauris elit, porttitor et magna vel, venenatis egestas diam. aliquam eleifend dictum iaculis. nunc placerat tortor orci, id commodo nisl pulvinar mattis. duis a sem consequat eros ornare feugiat. proin tempor arcu feugiat dignissim maximus. pellentesque tincidunt congue odio, ac gravida nulla. aliquam eu iaculis massa. donec vitae dui ut eros fermentum suscipit quis id nibh. proin et posuere libero. suspendisse potenti. nulla ornare viverra massa sed molestie. fusce dignissim tellus scelerisque aliquam efficitur.",
      nickname: "sewer22",
      image: "/bad-path.fail",
      area: "skinnarila",
      timedate: "11/01/2024, 12:13",
      location: "approximate location here, not sure how it should be saved",
    },
    {
      id: 4,
      title: "need a carjack in the weekend in skinnarila region!",
      type: "looking for...",
      ingress: "lorem upsum",
      description:
        "additional information and description related to the notice. lorem ipsum dolor sit amet, consectetur adipiscing elit. vestibulum consequat efficitur felis, ut feugiat justo cursus et. maecenas dapibus dictum eros vel lacinia. proin suscipit posuere purus vitae eleifend. maecenas mauris elit, porttitor et magna vel, venenatis egestas diam. aliquam eleifend dictum iaculis. nunc placerat tortor orci, id commodo nisl pulvinar mattis. duis a sem consequat eros ornare feugiat. proin tempor arcu feugiat dignissim maximus. pellentesque tincidunt congue odio, ac gravida nulla. aliquam eu iaculis massa. donec vitae dui ut eros fermentum suscipit quis id nibh. proin et posuere libero. suspendisse potenti. nulla ornare viverra massa sed molestie. fusce dignissim tellus scelerisque aliquam efficitur.",
      nickname: "carjacker22",
      area: "skinnarila",
      timedate: "11/01/2024, 12:13",
      location: "approximate location here, not sure how it should be saved",
    },
    {
      id: 5,
      title: "need a carjack in the weekend in skinnarila region!",
      type: "looking for...",
      ingress: "lorem upsum",
      description:
        "additional information and description related to the notice. lorem ipsum dolor sit amet, consectetur adipiscing elit. vestibulum consequat efficitur felis, ut feugiat justo cursus et. maecenas dapibus dictum eros vel lacinia. proin suscipit posuere purus vitae eleifend. maecenas mauris elit, porttitor et magna vel, venenatis egestas diam. aliquam eleifend dictum iaculis. nunc placerat tortor orci, id commodo nisl pulvinar mattis. duis a sem consequat eros ornare feugiat. proin tempor arcu feugiat dignissim maximus. pellentesque tincidunt congue odio, ac gravida nulla. aliquam eu iaculis massa. donec vitae dui ut eros fermentum suscipit quis id nibh. proin et posuere libero. suspendisse potenti. nulla ornare viverra massa sed molestie. fusce dignissim tellus scelerisque aliquam efficitur.",
      nickname: "carjacker22",
      area: "skinnarila",
      timedate: "11/01/2024, 12:13",
      location: "approximate location here, not sure how it should be saved",
    },
    {
      id: 6,
      title: "need a carjack in the weekend in skinnarila region!",
      type: "looking for...",
      ingress: "lorem upsum",
      description:
        "additional information and description related to the notice. lorem ipsum dolor sit amet, consectetur adipiscing elit. vestibulum consequat efficitur felis, ut feugiat justo cursus et. maecenas dapibus dictum eros vel lacinia. proin suscipit posuere purus vitae eleifend. maecenas mauris elit, porttitor et magna vel, venenatis egestas diam. aliquam eleifend dictum iaculis. nunc placerat tortor orci, id commodo nisl pulvinar mattis. duis a sem consequat eros ornare feugiat. proin tempor arcu feugiat dignissim maximus. pellentesque tincidunt congue odio, ac gravida nulla. aliquam eu iaculis massa. donec vitae dui ut eros fermentum suscipit quis id nibh. proin et posuere libero. suspendisse potenti. nulla ornare viverra massa sed molestie. fusce dignissim tellus scelerisque aliquam efficitur.",
      nickname: "carjacker22",
      area: "skinnarila",
      timedate: "11/01/2024, 12:13",
      location: "approximate location here, not sure how it should be saved",
    },
    {
      id: 7,
      title: "need a carjack in the weekend in skinnarila region!",
      type: "looking for...",
      ingress: "lorem upsum",
      description:
        "additional information and description related to the notice. lorem ipsum dolor sit amet, consectetur adipiscing elit. vestibulum consequat efficitur felis, ut feugiat justo cursus et. maecenas dapibus dictum eros vel lacinia. proin suscipit posuere purus vitae eleifend. maecenas mauris elit, porttitor et magna vel, venenatis egestas diam. aliquam eleifend dictum iaculis. nunc placerat tortor orci, id commodo nisl pulvinar mattis. duis a sem consequat eros ornare feugiat. proin tempor arcu feugiat dignissim maximus. pellentesque tincidunt congue odio, ac gravida nulla. aliquam eu iaculis massa. donec vitae dui ut eros fermentum suscipit quis id nibh. proin et posuere libero. suspendisse potenti. nulla ornare viverra massa sed molestie. fusce dignissim tellus scelerisque aliquam efficitur.",
      nickname: "carjacker22",
      area: "skinnarila",
      timedate: "11/01/2024, 12:13",
      location: "approximate location here, not sure how it should be saved",
    },
    {
      id: 8,
      title: "need a carjack in the weekend in skinnarila region!",
      type: "looking for...",
      ingress: "lorem upsum",
      description:
        "additional information and description related to the notice. lorem ipsum dolor sit amet, consectetur adipiscing elit. vestibulum consequat efficitur felis, ut feugiat justo cursus et. maecenas dapibus dictum eros vel lacinia. proin suscipit posuere purus vitae eleifend. maecenas mauris elit, porttitor et magna vel, venenatis egestas diam. aliquam eleifend dictum iaculis. nunc placerat tortor orci, id commodo nisl pulvinar mattis. duis a sem consequat eros ornare feugiat. proin tempor arcu feugiat dignissim maximus. pellentesque tincidunt congue odio, ac gravida nulla. aliquam eu iaculis massa. donec vitae dui ut eros fermentum suscipit quis id nibh. proin et posuere libero. suspendisse potenti. nulla ornare viverra massa sed molestie. fusce dignissim tellus scelerisque aliquam efficitur.",
      nickname: "carjacker22",
      area: "skinnarila",
      timedate: "11/01/2024, 12:13",
      location: "approximate location here, not sure how it should be saved",
    },
    {
      id: 9,
      title: "need a carjack in the weekend in skinnarila region!",
      type: "looking for...",
      ingress: "lorem upsum",
      description:
        "additional information and description related to the notice. lorem ipsum dolor sit amet, consectetur adipiscing elit. vestibulum consequat efficitur felis, ut feugiat justo cursus et. maecenas dapibus dictum eros vel lacinia. proin suscipit posuere purus vitae eleifend. maecenas mauris elit, porttitor et magna vel, venenatis egestas diam. aliquam eleifend dictum iaculis. nunc placerat tortor orci, id commodo nisl pulvinar mattis. duis a sem consequat eros ornare feugiat. proin tempor arcu feugiat dignissim maximus. pellentesque tincidunt congue odio, ac gravida nulla. aliquam eu iaculis massa. donec vitae dui ut eros fermentum suscipit quis id nibh. proin et posuere libero. suspendisse potenti. nulla ornare viverra massa sed molestie. fusce dignissim tellus scelerisque aliquam efficitur.",
      nickname: "carjacker22",
      area: "skinnarila",
      timedate: "11/01/2024, 12:13",
      location: "approximate location here, not sure how it should be saved",
    },
  ],
};
